// File: internal/config/default_typemaps.go
package config

// defaultTypeMappingsProvider menyediakan konfigurasi pemetaan tipe default yang disematkan.
// Semua pemetaan tipe data antar dialek didefinisikan di sini secara internal.
func defaultTypeMappingsProvider() *AllTypeMappings {
	return &AllTypeMappings{
		Mappings: []TypeMappingConfigEntry{
			{
				SourceDialect: "mysql",
				TargetDialect: "postgres",
				Mappings: map[string]StandardTypeMapping{
					"bit":        {TargetType: "VARBIT", ModifierHandling: ModifierHandlingApplySource},
					"tinyint":    {TargetType: "SMALLINT", ModifierHandling: ModifierHandlingApplySource}, // Default, tinyint(1) dihandle special
					"smallint":   {TargetType: "SMALLINT", ModifierHandling: ModifierHandlingApplySource},
					"mediumint":  {TargetType: "INTEGER", ModifierHandling: ModifierHandlingApplySource},
					"int":        {TargetType: "INTEGER", ModifierHandling: ModifierHandlingApplySource},
					"integer":    {TargetType: "INTEGER", ModifierHandling: ModifierHandlingApplySource},
					"bigint":     {TargetType: "BIGINT", ModifierHandling: ModifierHandlingApplySource},
					"float":      {TargetType: "REAL", ModifierHandling: ModifierHandlingApplySource},
					"double":     {TargetType: "DOUBLE PRECISION", ModifierHandling: ModifierHandlingApplySource},
					"decimal":    {TargetType: "NUMERIC", ModifierHandling: ModifierHandlingApplySource},
					"numeric":    {TargetType: "NUMERIC", ModifierHandling: ModifierHandlingApplySource},
					"char":       {TargetType: "CHAR", ModifierHandling: ModifierHandlingApplySource},
					"varchar":    {TargetType: "VARCHAR", ModifierHandling: ModifierHandlingApplySource},
					"tinytext":   {TargetType: "TEXT", ModifierHandling: ModifierHandlingIgnoreSource},
					"text":       {TargetType: "TEXT", ModifierHandling: ModifierHandlingIgnoreSource},
					"mediumtext": {TargetType: "TEXT", ModifierHandling: ModifierHandlingIgnoreSource},
					"longtext":   {TargetType: "TEXT", ModifierHandling: ModifierHandlingIgnoreSource},
					"binary":     {TargetType: "BYTEA", ModifierHandling: ModifierHandlingApplySource},
					"varbinary":  {TargetType: "BYTEA", ModifierHandling: ModifierHandlingApplySource},
					"tinyblob":   {TargetType: "BYTEA", ModifierHandling: ModifierHandlingIgnoreSource},
					"blob":       {TargetType: "BYTEA", ModifierHandling: ModifierHandlingIgnoreSource},
					"mediumblob": {TargetType: "BYTEA", ModifierHandling: ModifierHandlingIgnoreSource},
					"longblob":   {TargetType: "BYTEA", ModifierHandling: ModifierHandlingIgnoreSource},
					"json":       {TargetType: "JSONB", ModifierHandling: ModifierHandlingIgnoreSource},
					"enum":       {TargetType: "VARCHAR(255)", ModifierHandling: ModifierHandlingUseTargetDefined},
					"set":        {TargetType: "TEXT", ModifierHandling: ModifierHandlingIgnoreSource},
					"date":       {TargetType: "DATE", ModifierHandling: ModifierHandlingIgnoreSource},
					"time":       {TargetType: "TIME WITHOUT TIME ZONE", ModifierHandling: ModifierHandlingApplySource},
					"datetime":   {TargetType: "TIMESTAMP WITHOUT TIME ZONE", ModifierHandling: ModifierHandlingApplySource, PostgresUsingExpr: "CAST(REPLACE(CAST({{column_name}} AS TEXT), ' ', 'T') AS TIMESTAMP WITHOUT TIME ZONE)"},
					"timestamp":  {TargetType: "TIMESTAMP WITH TIME ZONE", ModifierHandling: ModifierHandlingApplySource},
					"year":       {TargetType: "SMALLINT", ModifierHandling: ModifierHandlingIgnoreSource},
					"geometry":   {TargetType: "geometry", ModifierHandling: ModifierHandlingIgnoreSource},
					"point":      {TargetType: "point", ModifierHandling: ModifierHandlingIgnoreSource},
					"linestring": {TargetType: "geometry", ModifierHandling: ModifierHandlingIgnoreSource},
					"polygon":    {TargetType: "geometry", ModifierHandling: ModifierHandlingIgnoreSource},
				},
				SpecialMappings: []SpecialMapping{
					{
						SourceTypePattern: "^tinyint\\(1\\)$",
						TargetType:        "BOOLEAN",
						ModifierHandling:  ModifierHandlingUseTargetDefined,
					},
				},
			},
			{
				SourceDialect: "postgres",
				TargetDialect: "mysql",
				Mappings: map[string]StandardTypeMapping{
					"smallint":         {TargetType: "SMALLINT", ModifierHandling: ModifierHandlingApplySource},
					"integer":          {TargetType: "INT", ModifierHandling: ModifierHandlingApplySource},
					"bigint":           {TargetType: "BIGINT", ModifierHandling: ModifierHandlingApplySource},
					"real":             {TargetType: "FLOAT", ModifierHandling: ModifierHandlingApplySource},
					"double precision": {TargetType: "DOUBLE", ModifierHandling: ModifierHandlingApplySource},
					"numeric":          {TargetType: "DECIMAL", ModifierHandling: ModifierHandlingApplySource},
					"decimal":          {TargetType: "DECIMAL", ModifierHandling: ModifierHandlingApplySource},
					"smallserial":      {TargetType: "SMALLINT", ModifierHandling: ModifierHandlingIgnoreSource},
					"serial":           {TargetType: "INT", ModifierHandling: ModifierHandlingIgnoreSource},
					"bigserial":        {TargetType: "BIGINT", ModifierHandling: ModifierHandlingIgnoreSource},
					"varchar":          {TargetType: "VARCHAR", ModifierHandling: ModifierHandlingApplySource},
					"char":             {TargetType: "CHAR", ModifierHandling: ModifierHandlingApplySource},
					"text":             {TargetType: "LONGTEXT", ModifierHandling: ModifierHandlingIgnoreSource},
					"bytea":            {TargetType: "LONGBLOB", ModifierHandling: ModifierHandlingIgnoreSource},
					"json":             {TargetType: "JSON", ModifierHandling: ModifierHandlingIgnoreSource},
					"jsonb":            {TargetType: "JSON", ModifierHandling: ModifierHandlingIgnoreSource},
					"uuid":             {TargetType: "CHAR(36)", ModifierHandling: ModifierHandlingUseTargetDefined},
					"date":             {TargetType: "DATE", ModifierHandling: ModifierHandlingIgnoreSource},
					"time":             {TargetType: "TIME", ModifierHandling: ModifierHandlingApplySource},
					"timetz":           {TargetType: "TIME", ModifierHandling: ModifierHandlingApplySource},
					"timestamp":        {TargetType: "DATETIME", ModifierHandling: ModifierHandlingApplySource},
					"timestamptz":      {TargetType: "TIMESTAMP", ModifierHandling: ModifierHandlingApplySource},
					"bool":             {TargetType: "TINYINT(1)", ModifierHandling: ModifierHandlingUseTargetDefined},
					"interval":         {TargetType: "VARCHAR(100)", ModifierHandling: ModifierHandlingUseTargetDefined},
					"money":            {TargetType: "DECIMAL(19,2)", ModifierHandling: ModifierHandlingUseTargetDefined},
					"bit":              {TargetType: "BIT", ModifierHandling: ModifierHandlingApplySource},
					"varbit":           {TargetType: "VARBINARY", ModifierHandling: ModifierHandlingApplySource},
					"inet":             {TargetType: "VARCHAR(43)", ModifierHandling: ModifierHandlingUseTargetDefined},
					"cidr":             {TargetType: "VARCHAR(43)", ModifierHandling: ModifierHandlingUseTargetDefined},
					"macaddr":          {TargetType: "VARCHAR(17)", ModifierHandling: ModifierHandlingUseTargetDefined},
					"macaddr8":         {TargetType: "VARCHAR(23)", ModifierHandling: ModifierHandlingUseTargetDefined},
					"text[]":           {TargetType: "JSON", ModifierHandling: ModifierHandlingIgnoreSource},
					"varchar[]":        {TargetType: "JSON", ModifierHandling: ModifierHandlingIgnoreSource},
					"integer[]":        {TargetType: "JSON", ModifierHandling: ModifierHandlingIgnoreSource},
					"bigint[]":         {TargetType: "JSON", ModifierHandling: ModifierHandlingIgnoreSource},
					"boolean[]":        {TargetType: "JSON", ModifierHandling: ModifierHandlingIgnoreSource},
					"numeric[]":        {TargetType: "JSON", ModifierHandling: ModifierHandlingIgnoreSource},
					"date[]":           {TargetType: "JSON", ModifierHandling: ModifierHandlingIgnoreSource},
					"timestamp[]":      {TargetType: "JSON", ModifierHandling: ModifierHandlingIgnoreSource},
					"timestamptz[]":    {TargetType: "JSON", ModifierHandling: ModifierHandlingIgnoreSource},
					"int2":             {TargetType: "SMALLINT", ModifierHandling: ModifierHandlingApplySource},
					"int4":             {TargetType: "INT", ModifierHandling: ModifierHandlingApplySource},
					"int8":             {TargetType: "BIGINT", ModifierHandling: ModifierHandlingApplySource},
					"float4":           {TargetType: "FLOAT", ModifierHandling: ModifierHandlingApplySource},
					"float8":           {TargetType: "DOUBLE", ModifierHandling: ModifierHandlingApplySource},
					"bpchar":           {TargetType: "CHAR", ModifierHandling: ModifierHandlingApplySource},
					"geometry":         {TargetType: "GEOMETRY", ModifierHandling: ModifierHandlingIgnoreSource},
					"point":            {TargetType: "POINT", ModifierHandling: ModifierHandlingIgnoreSource},
					"linestring":       {TargetType: "LINESTRING", ModifierHandling: ModifierHandlingIgnoreSource},
					"polygon":          {TargetType: "POLYGON", ModifierHandling: ModifierHandlingIgnoreSource},
				},
				SpecialMappings: []SpecialMapping{},
			},
			{
				SourceDialect: "sqlite",
				TargetDialect: "postgres",
				Mappings: map[string]StandardTypeMapping{
					"integer":   {TargetType: "BIGINT", ModifierHandling: ModifierHandlingIgnoreSource},
					"real":      {TargetType: "DOUBLE PRECISION", ModifierHandling: ModifierHandlingIgnoreSource},
					"text":      {TargetType: "TEXT", ModifierHandling: ModifierHandlingIgnoreSource},
					"blob":      {TargetType: "BYTEA", ModifierHandling: ModifierHandlingIgnoreSource},
					"numeric":   {TargetType: "NUMERIC", ModifierHandling: ModifierHandlingIgnoreSource},
					"int":       {TargetType: "BIGINT", ModifierHandling: ModifierHandlingIgnoreSource},
					"varchar":   {TargetType: "TEXT", ModifierHandling: ModifierHandlingIgnoreSource},
					"char":      {TargetType: "TEXT", ModifierHandling: ModifierHandlingIgnoreSource},
					"datetime":  {TargetType: "TIMESTAMP WITHOUT TIME ZONE", ModifierHandling: ModifierHandlingIgnoreSource},
					"date":      {TargetType: "DATE", ModifierHandling: ModifierHandlingIgnoreSource},
					"timestamp": {TargetType: "TIMESTAMP WITHOUT TIME ZONE", ModifierHandling: ModifierHandlingIgnoreSource},
					"boolean":   {TargetType: "BOOLEAN", ModifierHandling: ModifierHandlingIgnoreSource},
					"decimal":   {TargetType: "NUMERIC", ModifierHandling: ModifierHandlingIgnoreSource},
				},
				SpecialMappings: []SpecialMapping{},
			},
			{
				SourceDialect: "sqlite",
				TargetDialect: "mysql",
				Mappings: map[string]StandardTypeMapping{
					"integer":   {TargetType: "BIGINT", ModifierHandling: ModifierHandlingIgnoreSource},
					"real":      {TargetType: "DOUBLE", ModifierHandling: ModifierHandlingIgnoreSource},
					"text":      {TargetType: "LONGTEXT", ModifierHandling: ModifierHandlingIgnoreSource},
					"blob":      {TargetType: "LONGBLOB", ModifierHandling: ModifierHandlingIgnoreSource},
					"numeric":   {TargetType: "DECIMAL(38,18)", ModifierHandling: ModifierHandlingUseTargetDefined},
					"int":       {TargetType: "BIGINT", ModifierHandling: ModifierHandlingIgnoreSource},
					"varchar":   {TargetType: "LONGTEXT", ModifierHandling: ModifierHandlingIgnoreSource},
					"char":      {TargetType: "LONGTEXT", ModifierHandling: ModifierHandlingIgnoreSource},
					"datetime":  {TargetType: "DATETIME(6)", ModifierHandling: ModifierHandlingUseTargetDefined},
					"date":      {TargetType: "DATE", ModifierHandling: ModifierHandlingIgnoreSource},
					"timestamp": {TargetType: "DATETIME(6)", ModifierHandling: ModifierHandlingUseTargetDefined},
					"boolean":   {TargetType: "TINYINT(1)", ModifierHandling: ModifierHandlingUseTargetDefined},
					"decimal":   {TargetType: "DECIMAL(38,18)", ModifierHandling: ModifierHandlingUseTargetDefined},
				},
				SpecialMappings: []SpecialMapping{},
			},
		},
	}
}
