name: Go Test

on:
  push:
    branches: [ unit_test ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'

      - name: Check out code
        uses: actions/checkout@v3

      - name: Run Go Tests
        run: go test -v ./...
        # run: go test -v ./internal/...
